import AbilityStage from '@ohos.app.ability.AbilityStage';
import Want from '@ohos.app.ability.Want';

export default class MyAbilityStage extends AbilityStage {
  onAcceptWant(want: Want): string {
    // 在被调用方的AbilityStage中，针对启动模式为specified的UIAbility返回一个UIAbility实例对应的一个Key值
    // 当前示例指的是module1 Module的FuncAbility
    if (want.abilityName === 'DocumentAbility') {
      // 返回的字符串Key标识为自定义拼接的字符串内容
      return `DocAbilityInstance_${want.parameters.instanceKey}`;
    }

    return '';
  }
}